### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by jbridgenet** [Dahkenangnon/flutter_feathersjs.dart#45]
Connection error
It seems you are trying to reach a Socket.IO server in v2.x with a v3.x client, but they are not compatible (more information here:
https://socket.io/docs/v3/migrating-from-2-x-to-3-0/)

compiled your demo depo, then connected to your: https://flutter-feathersjs.herokuapp.com

**Comment by Dahkenangnon** [comment]
> Edit

Hello @jbridgenet , thank for your feedback.
Can you please be more clear ? What's the issue and how to do you encounter it. 

The issue is related to this package or about the demo app ?

**Comment by Dahkenangnon** [comment]
Any idea, fix, migration, contribution (PR) are welcome for this issue.

By these moment, I'm very busy because of my current job. So I cannot fix this before january.


So any help are welcome 

PS: Join this telegram group for pratical discussion: https://t.me/flutter_featherjs

**Comment by biloo-dev** [comment]
yo can solve this issue just downgrade this package to `socket_io_client: ^1.0.2`

**Comment by Dahkenangnon** [comment]
Try using directly this branch: https://github.com/Dahkenangnon/flutter_feathersjs.dart/tree/Socket.IO-v2.x-V3.x in your pubspec.yaml , latest commit.

Because if your server and compliant to the socketio client in the main branch, you should get always this error.

So opt for:

- above solution
- update your feathers js server
